### ISSUE TITLE
Procedural Datasets with Blender doesn't work with newer Blender versions

### ISSUE THREAD

**Issue by jmackay2** [gazebosim/gz-sim#2588]
## Environment
* OS Version: Ubuntu 24.04
* Source or binary build?
  Binary build of Ionic

<details>
I am unable to run Generation of Procedure Datasets with Blender with a newer version of Blender. 

I tested with Blender 4.2. 

It looks like the GeometryNodeTree objects in Blender have changed. 

</details>

## Description
* Expected behavior: Be able to run the blender [procedural datasets tutorial](https://gazebosim.org/api/sim/9/blender_procedural_datasets.html). 

## Steps to reproduce
1. Follow Option A in the precedural datasets tutorial, using [procedural_dataset_generator.py](https://github.com/gazebosim/gz-sim/blob/main/examples/scripts/blender/procedural_dataset_generator.py).

## Output

```
Python: Traceback (most recent call last):
  File "rock.blend/procedural_dataset_generator.py", line 1945, in <module>
  File "rock.blend/procedural_dataset_generator.py", line 1627, in main
  File "rock.blend/procedural_dataset_generator.py", line 1468, in generate
  File "rock.blend/procedural_dataset_generator.py", line 703, in export
  File "rock.blend/procedural_dataset_generator.py", line 832, in _process_meshes
  File "rock.blend/procedural_dataset_generator.py", line 859, in _export_geometry
  File "rock.blend/procedural_dataset_generator.py", line 899, in _export_geometry_collision
  File "rock.blend/procedural_dataset_generator.py", line 1494, in _pre_export_geometry_collision
  File "rock.blend/procedural_dataset_generator.py", line 1569, in _try_set_nodes_input_attribute
AttributeError: 'GeometryNodeTree' object has no attribute 'inputs'
```

**Comment by strangerwhoisharborofdoom** [comment]
Hi @jmackay2! I'm a first-year Robotics Engineering student and I'd like to contribute to fixing this Blender compatibility issue.

I can see the error is `AttributeError: 'GeometryNodeTree' object has no attribute 'inputs'` which suggests the Blender API has changed between versions. This is a common issue when Blender updates their geometry nodes API.

I'll start by:
1. Investigating the Blender API changes between the supported version and newer versions (4.x)
2. Finding where `GeometryNodeTree.inputs` is being accessed in `procedural_dataset_generator.py`
3. Updating the code to use the new API or adding version compatibility checks
4. Testing with both older and newer Blender versions if possible

I've already contributed to gazebosim/gz-sim with PR #3367 (documenting ECM computational complexity), so I'm familiar with the contribution process.

Please let me know if there are any specific Blender versions I should prioritize for testing!

Thanks!
