### ISSUE TITLE
Gazebo crashes at exit after using the transform tool

### ISSUE THREAD

**Issue by azeey** [gazebosim/gz-sim#725]
## Environment
* OS Version: Ubuntu 18.04
* Source or binary build? Source (`main`, future Edifice)

## Description
* Expected behavior: Gazebo does not crash 
* Actual behavior: After using the transform tool to move an object and pressing play, exiting Gazebo via the gui or typing`ctrl-c` on the terminal causes it to segfault. The segfault seems to only happen if the Component Inspector is enabled.

## Steps to reproduce

1. `ign gazebo shapes.sdf`
2. Ensure that the Component Inspector is loaded
3. Using the transform tool, move the box object
4. Start simulation by pressing the play button
5. Exit gazebo

## Output

<details><summary>Backtrace</summary>

```
#0  0x00007ffff1f24cd7 in std::__atomic_base<int>::load (__m=std::memory_order_relaxed, this=0x7fff93580078) at /usr/include/c++/7/bits/atomic_base.h:396
#1  QAtomicOps<int>::load<int> (_q_value=...) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic_cxx11.h:227
#2  QBasicAtomicInteger<int>::load (this=0x7fff93580078) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qbasicatomic.h:102
#3  QtPrivate::RefCount::deref (this=0x7fff93580078) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qrefcount.h:66
#4  QByteArray::~QByteArray (this=0x7fffa800f370, __in_chrg=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h:462
#5  QList<QByteArray>::node_destruct (this=<optimized out>, to=0x7fffa800f370, from=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:496
#6  QList<QByteArray>::dealloc (data=0x7fffa800f360, this=<optimized out>) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:865
#7  0x00007ffff211afce in QQmlPropertyCache::~QQmlPropertyCache (this=0x555557a59fe0, __in_chrg=<optimized out>) at qml/qqmlpropertycache.cpp:269
#8  0x00007ffff211b419 in QQmlPropertyCache::~QQmlPropertyCache (this=0x555557a59fe0, __in_chrg=<optimized out>) at qml/qqmlpropertycache.cpp:282
#9  0x00007ffff20e7462 in QQmlRefCount::destroy (this=<optimized out>) at ../../include/QtQml/5.9.5/QtQml/private/../../../../../src/qml/qml/ftw/qqmlrefcount_p.h:135
#10 QQmlRefCount::release (this=<optimized out>) at ../../include/QtQml/5.9.5/QtQml/private/../../../../../src/qml/qml/ftw/qqmlrefcount_p.h:125
#11 QQmlMetaTypeData::~QQmlMetaTypeData (this=0x7ffff2480f40 <(anonymous namespace)::Q_QGS_metaTypeData::innerFunction()::holder>, __in_chrg=<optimized out>) at qml/qqmlmetatype.cpp:162
#12 0x00007ffff20e7489 in (anonymous namespace)::Q_QGS_metaTypeData::Holder::~Holder (this=<optimized out>, __in_chrg=<optimized out>) at qml/qqmlmetatype.cpp:144
#13 0x00007ffff7574161 in __run_exit_handlers (status=0, listp=0x7ffff791c718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#14 0x00007ffff757425a in __GI_exit (status=<optimized out>) at exit.c:139
#15 0x00007ffff7552bfe in __libc_start_main (main=0x555555554880, argc=5, argv=0x7fffffffd558, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd548) at ../csu/libc-start.c:344
#16 0x00005555555548fa in _start ()

```

</details>

**Comment by azeey** [comment]
This appears to be fixed in my testing, so I'll go ahead and close.
